### ISSUE TITLE
Greek transcription errors

### ISSUE THREAD

**Issue by johnfactotum** [standardebooks/plato_dialogues_benjamin-jowett#3]
There are many errors in the Greek text. The most common problems seem to be mistaking `ω` for `w`, `υ` for `ν`, and using `ϕ` (U+03D5) instead of `φ` (U+03C6). A few examples from `preface-2.xhtml`:

|Current|Expected|
|-|-|
|ω̂̔ν καὶ νν̂ν|ὧν καὶ νῦν|
|τŵν πολιτŵν|τῶν πολιτῶν|
|σωϕροσύνη|σωφροσύνη|

And it almost always uses the circumflex accent instead of the *perispomeni*. Although the accent is commonly known as the circumflex accent, the *perispomeni* is usually rendered as a tilde or an inverted breve.
|Current|Expected|
|-|-|
|πολλη̂ς πείρας τελευταîον|πολλῆς πείρας τελευταῖον|

**Comment by acabal** [comment]
Yes, I'm not surprised, I don't think we have anyone in the project who actually speaks Greek so we're all just eyeballing it and errors are going to be inevitable.

You can submit a PR for the corrections you found if you'd like.

We do have a lint check for spans of non-Latin languages that contain Latin script characters, and that check shakes out a majority of the incorrect transliterations. But it's a simple regex match of `[a-zA-Z]` so it doesn't catch cases with combining marks like here. [These are the lines that do this](https://github.com/standardebooks/tools/blob/master/se/se_epub_lint.py#L2268C11-L2270), if you think there's a better way to automatically catch some errors like these.

**Comment by acabal** [comment]
I'm also open other ideas for how to create/improve automated checks for things like this. Greek script is fairly common in a lot of these works so an automated check that a non-Greek speaker could use would be very helpful, even if it's not 100% perfect.

**Comment by johnfactotum** [comment]
I found a [hunspell dictionary for Ancient Greek](https://github.com/mrakia/hunspell-ancient-greek). It doesn't catch the symbols (e.g. `ϕ` vs `φ`), though, which I guess is probably due to those being treated as canonically equivalent to the lowercase letters by hunspell.

**Comment by acabal** [comment]
That might be an option, though we'd need someone to do the work to integrate it. And I don't know how helpful would be if the solution isn't able to differentiate between ancient Greek or modern Greek, since our producers aren't going to be able to tell the difference. In other words, whether a producer selects `el` or `grc` is going to be an educated guess at absolute best. So the solution must be able to somehow make the correct choice there automatically. Or is there even any material difference?

**Comment by johnfactotum** [comment]
Perhaps it would be enough to spellcheck it both as Modern Greek and Ancient Greek.

- If it's only correct for one of them, then that's probably it.
- If it's correct for both, it either doesn't matter, or one should be able to determine from context.
- If it's incorrect for both, then first see if there are diacritics. If the text is polytonic, that is, if it has any accents other than the acute, then it's Ancient Greek. If it's monotonic, it could be either.

In any case it should probably decompose (normalize) the string first. Then you should be able to flag and correct any Latin characters or diacritics easily.
